M48
; DRILL file {KiCad (6.0.11)} date Wed Oct  9 23:58:56 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-09T23:58:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.000
%
G90
G05
T1
X175.242Y-80.872
X175.242Y-88.852
T2
X148.501Y-102.004
T0
M30
